workspaces:
    - name: default
      path: /Users/ricky
      aliases:
        cr: github.com/github/container-registry
        d: dotfiles
        dotcom: gh
        nr: github.com/github/npm-registry
        p: c2c-package-registry
        rms: github.com/github/registry-metadata
      custom:
        dotfiles: /Users/ricky/.dotfiles
        gh: /Users/ricky/gh/github
        ghes: /Users/ricky/gh/enterprise2
