#!/usr/bin/env bash

set -e
set -x

cd "$(dirname "$0")/.."

git submodule update --init --recursive
git submodule update --remote dotdrop

if command -v python3; then
    python3 -m venv env
    source env/bin/activate
    pip install -r dotdrop/requirements.txt
    deactivate
else
    echo "Python3 must be installed" >&2
    exit 2
fi

case "$(uname -s)" in
    Darwin)       
	ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
	brew tap caskroom/cask
	source ./script/brew.sh
	;;
    
    Linux)
	sudo apt-get -y install python3-venv zsh
	;;
esac

# Install oh-my-zsh
if command -v curl; then
  sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
elif command -v wget; then
  sh -c "$(wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"
else
  abort "Either curl or wget must be installed"
fi
