#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

case "$(uname -s)" in
    Darwin)
        ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        brew tap caskroom/cask
        source ./script/brew.sh
        ;;

    Linux)
        sudo apt-get update
        source ./script/apt-get.sh
        ;;
esac

git submodule update --init --recursive
git submodule update --remote dotdrop

if command -v python3; then
    python3 -m venv env
    source env/bin/activate
    pip install -r dotdrop/requirements.txt
else
    echo "Python3 must be installed" >&2
    exit 2
fi

# TODO
./dotdrop.sh install --profile=home

deactivate

# Install oh-my-zsh
if command -v curl; then
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
elif command -v wget; then
    sh -c "$(wget -qO- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
else
    echo "either curl or wget must be installed" >&2
    exit 2
fi
